CREATE DATABASE catalog_of_my_things;

CREATE TABLE Books (
  id GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  genre_id INTEGER,
  author_id INTEGER,
  label_id INTEGER,
  published_date DATETIME NOT NULL,
  archived BOOLEAN NOT NULL DEFAULT FALSE,
  publisher VARCHAR(30) NOT NULL,
  cover_state VARCHAR(30) NOT NULL,
  FOREIGN KEY (genre_id) REFERENCES Genres(id),
  FOREIGN KEY (author_id) REFERENCES Authors(id),
  FOREIGN KEY (label_id) REFERENCES Labels(id)
)

CREATE TABLE Labels (
  id GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title VARCHAR(30) NOT NULL,
  color VARCHAR(20)
)
CREATE TABLE music_album (
    id int GENERATED BY DEFAULT AS IDENTITY,
    genre_id int
    publish_date date,
    archived boolean,
    on_spotify boolean,
    CONSTRAINT genre_fkey FOREIGN KEY (genre_id) REFERENCES genre(id),

)

CREATE TABLE genre (
    id int GENERATED BY DEFAULT AS IDENTITY,
    title varchar(50),
    genre varchar(50),
    CONSTRAINT genre_pk PRIMARY KEY (id)
)
)
